"""Optional critic agent skeleton for bonus work."""

from multi_agent_research_lab.agents.base import BaseAgent
from multi_agent_research_lab.core.errors import StudentTodoError
from multi_agent_research_lab.core.state import ResearchState


from multi_agent_research_lab.services.llm_client import LLMClient
from multi_agent_research_lab.core.schemas import AgentName, AgentResult


class CriticAgent(BaseAgent):
    """Optional fact-checking and safety-review agent."""

    name = "critic"

    def __init__(self) -> None:
        self.llm_client = LLMClient()

    def run(self, state: ResearchState) -> ResearchState:
        """Validate final answer and append findings."""
        query = state.request.query
        final_answer = state.final_answer or "No draft answer available."
        sources_text = ""
        for idx, doc in enumerate(state.sources):
            sources_text += f"Source [{idx}]:\nTitle: {doc.title}\nSnippet: {doc.snippet}\n\n"

        system_prompt = (
            "You are an expert Critic Agent. Your task is to review the draft final answer generated by the writer agent "
            "against the original source documents and the user query.\n"
            "Evaluate based on:\n"
            "1. Hallucinations: Are there any claims that cannot be supported by the snippets?\n"
            "2. Citation Accuracy: Are the sources cited correctly (e.g. [0], [1])?\n"
            "3. Completeness: Does the answer fully satisfy the user's query?\n\n"
            "Your output MUST begin with '[APPROVED]' if the draft is accurate and complete, "
            "or '[REJECTED]' followed by detailed constructive feedback on what needs to be fixed."
        )

        user_prompt = (
            f"User Query: {query}\n\n"
            f"Original Sources:\n{sources_text}\n"
            f"Draft Answer:\n{final_answer}"
        )

        response = self.llm_client.complete(system_prompt, user_prompt)

        approved = response.content.strip().startswith("[APPROVED]")
        metadata = {
            "approved": approved,
            "input_tokens": response.input_tokens,
            "output_tokens": response.output_tokens,
            "cost_usd": response.cost_usd,
        }
        state.agent_results.append(
            AgentResult(
                agent=AgentName.CRITIC,
                content=response.content,
                metadata=metadata
            )
        )

        return state
